services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    # networks:
    #   - proxy
    ports:
      # - 3000:3000/tcp # only required during initial setup
      - 8080:80/tcp # web interface after setup
      - 53:53/tcp # dns
      - 53:53/udp # dns
      # - 67:67/udp # dhcp
      # - 68:68/tcp # dhcp
      # - 68:68/udp # dhcp
      # - 784:784/udp # dns-over-quic
      # - 853:853/tcp # dns over tls
      # - 853:853/udp # dns over tls
      # - 5443:5443/tcp # dnscrypt
      # - 5443:5443/udp # dnscrypt
    volumes:
      - /srv/appdata/adguard/work:/opt/adguardhome/work
      - /srv/appdata/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ:-Europe/London}
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.adguard-rtr.entrypoints=https
    #   - traefik.http.routers.adguard-rtr.rule=Host(`adguard.${DOMAIN}`)
    #   - traefik.http.routers.adguard-rtr.service=adguard-svc
    #   - traefik.http.services.adguard-svc.loadbalancer.server.port=80
# networks:
#   proxy:
#     external: true
