services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    restart: always
    networks:
      - dns
      - proxy
    ports:
      # - 3000:3000/tcp # only required during initial setup
      - 8080:80/tcp # web interface after setup
      - 53:53/tcp # dns
      - 53:53/udp # dns
      # - 67:67/udp # dhcp
      # - 68:68/tcp # dhcp
      # - 68:68/udp # dhcp
      # - 784:784/udp # dns-over-quic
      # - 853:853/tcp # dns over tls
      # - 853:853/udp # dns over tls
      # - 5443:5443/tcp # dnscrypt
      # - 5443:5443/udp # dnscrypt
    volumes:
      - /srv/appdata/adguard/work:/opt/adguardhome/work
      - /srv/appdata/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ}
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=https
      - traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN}`)
      - traefik.http.routers.adguard.service=adguard
      - traefik.http.services.adguard.loadbalancer.server.port=80

  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound
    restart: always
    networks:
      dns:
        ipv4_address: 172.25.0.5
    # ports:
    #   - 5335:53/tcp # dns
    #   - 5335:53/udp # dns
    volumes:
      - /srv/appdata/unbound:/etc/unbound/custom.conf.d
    environment:
      - TZ=${TZ}

networks:
  dns:
    name: dns
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
  proxy:
    external: true
