all:
  hosts:
    pandora:
      ansible_host: pandora
    atlas:
      ansible_host: atlas
    janus:
      ansible_host: janus
    hyperion:
      ansible_host: hyperion
    dione:
      ansible_host: dione
    localhost:
      ansible_connection: local

  children:
    homelab_hosts:
      hosts:
        pandora:
        janus:
        atlas:
        hyperion:
        dione:
