---
- name: Ensure service directories exist
  hosts: "{{ service_directory_targets | default('all') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Gather services assigned to host
      ansible.builtin.set_fact:
        host_services: >-
          {{
            services | default({}) | dict2items
            | selectattr('value.hosts', 'defined')
            | selectattr('value.hosts', 'contains', inventory_hostname)
            | list
          }}

    # - name: Ensure compose directories exist
    #   when: host_services | length > 0
    #   ansible.builtin.include_tasks: tasks/ensure_compose_dir.yml
    #   loop: "{{ host_services }}"
    #   loop_control:
    #     loop_var: svc
    #     label: "{{ svc.key }}"

    - name: Ensure appdata directories exist
      when: host_services | length > 0
      ansible.builtin.include_tasks: tasks/ensure_appdata_dirs.yml
      loop: "{{ host_services }}"
      loop_control:
        loop_var: svc
        label: "{{ svc.key }}"

    - name: Ensure extra directories exist
      when: host_services | length > 0
      ansible.builtin.include_tasks: tasks/ensure_extra_dirs.yml
      loop: "{{ host_services }}"
      loop_control:
        loop_var: svc
        label: "{{ svc.key }}"
