---
- name: Ensure service directories exist
  hosts: "{{ service_directory_targets | default('all') }}"
  become: true
  gather_facts: false

  tasks:
    - name: Initialize host services list
      ansible.builtin.set_fact:
        host_services: []

    - name: Gather services assigned to host
      ansible.builtin.set_fact:
        host_services: "{{ host_services + [ { 'server': inventory_hostname, 'name': service.key, 'config': service.value } ] }}"
      loop: "{{ (servers[inventory_hostname] | default({})) | dict2items }}"
      loop_control:
        loop_var: service
        label: "{{ inventory_hostname }} -> {{ service.key }}"

    # - name: Ensure compose directories exist
    #   when: host_services | length > 0
    #   ansible.builtin.include_tasks: tasks/ensure_compose_dir.yml
    #   loop: "{{ host_services }}"
    #   loop_control:
    #     loop_var: svc
    #     label: "{{ svc.server }} / {{ svc.name }}"

    - name: Ensure appdata directories exist
      when: host_services | length > 0
      ansible.builtin.include_tasks: tasks/ensure_appdata_dirs.yml
      loop: "{{ host_services }}"
      loop_control:
        loop_var: svc
        label: "{{ svc.server }} / {{ svc.name }}"

    - name: Ensure extra directories exist
      when: host_services | length > 0
      ansible.builtin.include_tasks: tasks/ensure_extra_dirs.yml
      loop: "{{ host_services }}"
      loop_control:
        loop_var: svc
        label: "{{ svc.server }} / {{ svc.name }}"
