name: immich

services:
  server:
    image: ghcr.io/immich-app/immich-server:release
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - proxy
      - immich
    # ports:
    #   - 2283:2283
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Media location (originals + uploads)
      - /mnt/user/gallery/immich:/data
      # External library
      - /mnt/user/gallery/library:/mnt/media/library:ro
      # Hot paths
      - /mnt/user/appdata/immich/thumbs:/data/thumbs
      - /mnt/user/appdata/immich/encoded-video:/data/encoded-video
      - /mnt/user/appdata/immich/profile:/data/profile
      - /mnt/user/gallery/immich/backups:/data/backups
    environment:
      - TZ=${TZ}
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=${IMMICH_DB_PASSWORD}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.entrypoints=http
      - traefik.http.routers.immich.rule=Host(`photos.${DOMAIN}`)
      - traefik.http.routers.immich.service=immich
      - traefik.http.services.immich.loadbalancer.server.port=2283
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, video]

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    restart: unless-stopped
    networks:
      - immich
    volumes:
      - model-cache:/cache
      - /mnt/user/gallery/immich:/data:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  redis:
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    restart: unless-stopped
    networks:
      - immich
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    restart: unless-stopped
    networks:
      - immich
    volumes:
      - /mnt/user/appdata/immich/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${IMMICH_DB_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
      # - DB_STORAGE_TYPE=HDD # Uncomment If DB is on HDD
    shm_size: 128mb
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres -d immich"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

volumes:
  model-cache:

networks:
  immich:
    name: immich
  proxy:
    external: true
