services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    networks:
      - proxy
    # ports:
    #   - 8080:8080/tcp # ui
    #   - 6881:6881/tcp # torrent
    #   - 6881:6881/udp # torrent
    environment:
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - PUID=99
      - PGID=100
      - UMASK=000
    volumes:
      - /mnt/user/appdata/qbittorrent/config:/config
      - /mnt/user/downloads/torrents:/downloads
      - /mnt/user/downloads/torrents/watch:/watch
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.entrypoints=http
      - traefik.http.routers.qbittorrent.rule=Host(`torrent.${DOMAIN}`)
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080

networks:
  proxy:
    external: true
