services:
  traefik:
    image: traefik:latest
    container_name: traefik-janus
    restart: always
    depends_on:
      - socket-proxy
    networks:
      - proxy
      - docker-proxynet
    ports:
      # - 80:80/tcp # http
      - 443:443/tcp # https
      # - 443:443/udp # https http3 quic
      # - 8080:8080 # http api dashboard
      - 25565:25565/tcp # minecraft tcp entrypoint
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock:ro # better use socket-proxy instead
      - /srv/appdata/traefik/config:/etc/traefik/:ro # put the provided traefik.yml and dynamic folder here
      - /srv/appdata/traefik/certificates:/letsencrypt:rw
      - /srv/appdata/traefik/logs:/logs:rw
    environment:
      - TZ=${TZ:-Europe/London}
      - CF_DNS_API_TOKEN=${TRAEFIK_CF_DNS_API_TOKEN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-rtr.entrypoints=https
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik-rtr.service=api@internal
    security_opt:
      - no-new-privileges:true

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    restart: always
    networks:
      - docker-proxynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
      - EVENTS=1
    read_only: true
    tmpfs:
      - /run

networks:
  proxy:
    name: proxy
  docker-proxynet:
    internal: true
