---
# Secrets resolved from local environment.
domain: "{{ lookup('env', 'DOMAIN') | default('', true) | trim }}"
base_dn: "{{ lookup('env', 'BASE_DN') | default('', true) | trim }}"
domain_demos: "{{ lookup('env', 'DOMAIN_DEMOS') | default('', true) | trim }}"
acme_letsencrypt_url: "{{ lookup('env', 'TRAEFIK_ACME_LETSENCRYPT_URL') | default('', true) | trim }}"
acme_cert_email: "{{ lookup('env', 'TRAEFIK_ACME_CERT_EMAIL') | default('', true) | trim }}"
smtp_host: "{{ lookup('env', 'SMTP_HOST') | default('', true) | trim }}"
smtp_port: "{{ lookup('env', 'SMTP_PORT') | default('', true) | trim }}"
smtp_user: "{{ lookup('env', 'SMTP_USER') | default('', true) | trim }}"
smtp_sender: "{{ lookup('env', 'SMTP_SENDER') | default('', true) | trim }}"
authelia_lldap_password: "{{ lookup('env', 'AUTHELIA_LLDAP_PASSWORD') | default('', true) | trim }}"
