---
# Secrets resolved from local environment.
domain: "{{ lookup('env', 'DOMAIN') | default('', true) | trim }}"
domain_demos: "{{ lookup('env', 'DOMAIN_DEMOS') | default('', true) | trim }}"
acme_letsencrypt_url: "{{ lookup('env', 'TRAEFIK_ACME_LETSENCRYPT_URL') | default('', true) | trim }}"
acme_cert_email: "{{ lookup('env', 'TRAEFIK_ACME_CERT_EMAIL') | default('', true) | trim }}"
