http:
  routers:
    traefik-atlas:
      rule: "Host(`atlas.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-atlas
      middlewares:
        - authelia@docker
    cutter:
      rule: "Host(`cutter.{{ domain_demos }}`)"
      entryPoints:
        - https
      service: app-via-atlas

  services:
    app-via-atlas:
      loadBalancer:
        servers:
          - url: "http://atlas.home.local:80"
