http:
  routers:
    adguard:
      rule: "Host(`adguard.{{ domain }}`)"
      entryPoints:
        - https
      service: adguard

    traefik:
      rule: "Host(`traefik.{{ domain }}`)"
      entryPoints:
        - https
      service: api@internal

  services:
    adguard:
      loadBalancer:
        servers:
          - url: "http://janus.home.local:8080"
