tcp:
  routers:
    mantita:
      entryPoints:
        - minecraft
      rule: "HostSNI(`*`)"
      service: mantita

  services:
    mantita:
      loadBalancer:
        servers:
          - address: "pandora.home.local:25565"
