http:
  routers:
    adguard:
      rule: 'Host(`adguard.{{ env "TRAEFIK_DOMAIN" }}`)'
      entryPoints:
        - https
      service: adguard

    traefik:
      rule: 'Host(`traefik.{{ env "TRAEFIK_DOMAIN" }}`)'
      entryPoints:
        - https
      service: api@internal

  services:
    adguard:
      loadBalancer:
        servers:
          - url: "http://janus.home.local:8080"
