http:
  routers:
    traefik-pandora:
      rule: "Host(`pandora.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-pandora
      middlewares:
        - authelia@docker
    media:
      rule: "Host(`media.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-pandora
    minepanel:
      rule: "Host(`minepanel.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-pandora
    minepanel-api:
      rule: "Host(`minepanel-api.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-pandora
    torrent:
      rule: "Host(`torrent.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-pandora
      middlewares:
        - authelia@docker
    unraid:
      rule: "Host(`unraid.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-pandora
    chat:
      rule: "Host(`chat.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-pandora
    ai:
      rule: "Host(`ai.{{ domain }}`)"
      entryPoints:
        - https
      service: app-via-pandora

  services:
    app-via-pandora:
      loadBalancer:
        servers:
          - url: "http://pandora.home.local:80"

tcp:
  routers:
    mantita:
      entryPoints:
        - minecraft
      rule: "HostSNI(`*`)"
      service: mantita

  services:
    mantita:
      loadBalancer:
        servers:
          - address: "pandora.home.local:25565"
